const ACTIONS = {
	GET_USERS: "GET_USERS",
	SET_USERS: "SET_USERS",
	SET_COUNTRIES: "SET_COUNTRIES",
	SET_CITIES: "SET_CITIES",
	SET_FILTEREDUSERS: "SET_FILTEREDUSERS",
	ERROR: "ERROR",
};

export default ACTIONS;
